name: ASSIST Unit Tests (C)

on: [push, pull_request]

env:
  JPL_PLANET_EPHEM: ../../data/linux_p1550p2650.440

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download REBOUND
        working-directory: ../
        run: | 
          pwd
          git clone https://github.com/hannorein/rebound.git
          #- name: Compile REBOUND
          #  working-directory: ../rebound
          #  run: | 
          #    pwd
          #    make
          #- name: Compile ASSIST
          #  run: | 
          #    make
      - name: Download DE441 dataset
        working-directory: ./data/
        run: |
          #wget --no-verbose https://ssd.jpl.nasa.gov/ftp/eph/planets/Linux/de441/linux_m13000p17000.441  
          wget --no-verbose https://ssd.jpl.nasa.gov/ftp/eph/planets/Linux/de440/linux_p1550p2650.440
          wget --no-verbose https://ssd.jpl.nasa.gov/ftp/eph/small_bodies/asteroids_de441/sb441-n16.bsp
      - name: Reproduce Holman trajectory
        working-directory: ./unit_tests/holman/
        run: |
          make
          LD_LIBRARY_PATH=../../../rebound/src/ ./rebound
      - name: Reproduce Holman trajectory (backwards in time)
        working-directory: ./unit_tests/holman_reverse/
        run: |
          make
          LD_LIBRARY_PATH=../../../rebound/src/ ./rebound
      - name: Reproduce Apophis Encounter (non gravitational forces) 
        working-directory: ./unit_tests/apophis/
        run: |
          make
          LD_LIBRARY_PATH=../../../rebound/src/ ./rebound
      - name: Reproduce Ceres-5303 encounter 
        working-directory: ./unit_tests/5303_Ceres/
        run: |
          make
          LD_LIBRARY_PATH=../../../rebound/src/ ./rebound
      - name: Test interpolation 
        working-directory: ./unit_tests/interpolation/
        run: |
          make
          LD_LIBRARY_PATH=../../../rebound/src/ ./rebound
      - name: Test onthefly interpolation 
        working-directory: ./unit_tests/onthefly_interpolation/
        run: |
          make
          LD_LIBRARY_PATH=../../../rebound/src/ ./rebound
      - name: Test ephem_cache 
        working-directory: ./unit_tests/ephem_cache/
        run: |
          make
          LD_LIBRARY_PATH=../../../rebound/src/ ./rebound
      - name: Test roundtrip
        working-directory: ./unit_tests/roundtrip/
        run: |
          make
          LD_LIBRARY_PATH=../../../rebound/src/ ./rebound
      - name: Test roundtrip adaptive
        working-directory: ./unit_tests/roundtrip_adaptive/
        run: |
          make
          LD_LIBRARY_PATH=../../../rebound/src/ ./rebound
      - name: Run benchmark
        working-directory: ./unit_tests/benchmark
        run: |
          make
          LD_LIBRARY_PATH=../../../rebound/src/ ./rebound
